print("Welcome to the tip calculator!")
total = float(input("What was the total bill? $"))
percent = int(input("How much tip would you like to give? 10, 12, or 15?"))
split = int(input("How many people to split the bill?"))
tip = total * (percent / 100)
final = print(f"Each person should pay: ${round(((total + tip) / split), 2)}")